### ISSUE TITLE
Change repo settings to allow outside collaborators

### ISSUE THREAD

**Issue by Machione** [Edward-Blair/WebscraperRepo#1]
When attempting to push commits to a new branch I get

> ERROR: Permission to Edward-Blair/WebscraperRepo.git denied to Machione.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

I'm guessing something needs to be changed in the repository settings to allow pushes from outsiders?

**Comment by Edward-Blair** [comment]
You have now been invited as collaborator to this repo, which should allow for this.
